### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by vogelsara** [SakineMazlomyar/TechStore#13]
I recognized that we used wrong colors.
The defined colors (in the uppgiftbeskrivning):

• Blå: #5596F5
• Röd: #E64E4E
• Grå: #F5F5F5
• Vit: #FFFFFF
• Svart: #212121

And we used the colors of bootstrap. We need to overwrite theese colors. This task could be done by the end of the project with all of the css stuff. Don't make a big deal about of it i just noticed.

**Comment by MisticG** [comment]
👍
