### ISSUE TITLE
Making "ta bort"- button + functions

### ISSUE THREAD

**Issue by MisticG** [SakineMazlomyar/TechStore#7]
Made a branch for creating the code

https://github.com/SakineMazlomyar/TechStore/tree/deleteButtonFunctions

**Comment by tuyvi** [comment]
Made a branch for creating the code

**Comment by MisticG** [comment]
The button works and the counter works but need to figure out how to delete a specific product.

**Comment by MisticG** [comment]
Delete functions are successful! Let's check together and if it's all ok then I'll merge it with the master branch.

https://github.com/SakineMazlomyar/TechStore/tree/deleteButtonFunctions

**Comment by MisticG** [comment]
Need to add a trash can icon on the button
